In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
data = files.upload()

Saving 02Students (1).csv to 02Students (1).csv


In [3]:
df = pd.read_csv('02Students (1).csv')

In [4]:
df

Hours  sHours  Marks
0       0       6     34
1       1       7     36
2       1       6     33
3       1       8     39
4       1       8     42
5       2       8     45
6       2       6     38
7       3       6     45
8       3       7     53
9       3       7     46
10      3       8     56
11      4       8     59
12      4       7     55
13      4       7     56
14      5       8     72
15      5       6     59
16      6       6     62
17      6       7     71
18      7       8     78
19      7       8     88
20      7       6     61
21      7       6     74
22      8       7     71
23      8       8     89
24      9       8     82
25      9       5     67
26      9       8     89
27     10       8     81
28     10       8     82
29     11       7     79

In [ ]:
df.head()

Hours  sHours  Marks
0      0       6     34
1      1       7     36
2      1       6     33
3      1       8     39
4      1       8     42

In [ ]:
df.tail()

Hours  sHours  Marks
25      9       5     67
26      9       8     89
27     10       8     81
28     10       8     82
29     11       7     79

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Hours   30 non-null     int64
 1   sHours  30 non-null     int64
 2   Marks   30 non-null     int64
dtypes: int64(3)
memory usage: 848.0 bytes


In [ ]:
df.columns

Index(['Hours', 'sHours', 'Marks'], dtype='object')

In [ ]:
df.describe()

Hours     sHours      Marks
count  30.000000  30.000000  30.000000
mean    5.200000   7.100000  61.400000
std     3.188341   0.922889  17.734828
min     0.000000   5.000000  33.000000
25%     3.000000   6.000000  45.250000
50%     5.000000   7.000000  60.000000
75%     7.750000   8.000000  77.000000
max    11.000000   8.000000  89.000000

In [ ]:
df.shape

(30, 3)

In [ ]:
#Data Cleaning
df.isnull()

Hours  sHours  Marks
0   False   False  False
1   False   False  False
2   False   False  False
3   False   False  False
4   False   False  False
5   False   False  False
6   False   False  False
7   False   False  False
8   False   False  False
9   False   False  False
10  False   False  False
11  False   False  False
12  False   False  False
13  False   False  False
14  False   False  False
15  False   False  False
16  False   False  False
17  False   False  False
18  False   False  False
19  False   False  False
20  False   False  False
21  False   False  False
22  False   False  False
23  False   False  False
24  False   False  False
25  False   False  False
26  False   False  False
27  False   False  False
28  False   False  False
29  False   False  False

In [ ]:
#xy Split
x = df.iloc[:,:-1]

In [ ]:
x

Hours  sHours
0       0       6
1       1       7
2       1       6
3       1       8
4       1       8
5       2       8
6       2       6
7       3       6
8       3       7
9       3       7
10      3       8
11      4       8
12      4       7
13      4       7
14      5       8
15      5       6
16      6       6
17      6       7
18      7       8
19      7       8
20      7       6
21      7       6
22      8       7
23      8       8
24      9       8
25      9       5
26      9       8
27     10       8
28     10       8
29     11       7

In [ ]:
x = df.iloc[:,:-1].values

In [ ]:
x

array([[ 0,  6],
       [ 1,  7],
       [ 1,  6],
       [ 1,  8],
       [ 1,  8],
       [ 2,  8],
       [ 2,  6],
       [ 3,  6],
       [ 3,  7],
       [ 3,  7],
       [ 3,  8],
       [ 4,  8],
       [ 4,  7],
       [ 4,  7],
       [ 5,  8],
       [ 5,  6],
       [ 6,  6],
       [ 6,  7],
       [ 7,  8],
       [ 7,  8],
       [ 7,  6],
       [ 7,  6],
       [ 8,  7],
       [ 8,  8],
       [ 9,  8],
       [ 9,  5],
       [ 9,  8],
       [10,  8],
       [10,  8],
       [11,  7]])

In [ ]:
y = df.iloc[:,1].values

NameError: ignored

In [ ]:
y

array([6, 7, 6, 8, 8, 8, 6, 6, 7, 7, 8, 8, 7, 7, 8, 6, 6, 7, 8, 8, 6, 6,
       7, 8, 8, 5, 8, 8, 8, 7])

In [ ]:
#Train Test Split
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = 0.3, random_state=7)

In [ ]:
x_train.shape

(21, 2)

In [ ]:
#Model Building
from sklearn.linear_model import LinearRegression

In [ ]:
std_reg = LinearRegression()

In [ ]:
std_reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
#Model Evaluation Predict the Results
y_predict = std_reg.predict(x_test)

In [ ]:
y_predict

array([6., 7., 7., 7., 8., 8., 8., 8., 8.])

In [ ]:
y_test

array([6, 7, 7, 7, 8, 8, 8, 8, 8])