In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
files.upload()

Saving 01Exercise1.csv to 01Exercise1.csv


{'01Exercise1.csv': b'gender,married,ch,income,loanamt,status\r\nMale,No,1,5849,,Y\r\nMale,Yes,1,4583,128,N\r\nMale,Yes,1,3000,66,Y\r\nMale,Yes,1,2583,120,Y\r\nMale,No,1,6000,141,Y\r\nMale,Yes,1,5417,267,Y\r\nMale,Yes,1,2333,95,Y\r\nMale,Yes,0,3036,158,N\r\nMale,Yes,1,4006,168,Y\r\nMale,Yes,1,12841,349,N\r\nMale,Yes,1,3200,70,Y\r\nMale,Yes,1,2500,109,Y\r\nMale,Yes,1,3073,200,Y\r\nMale,No,1,1853,114,N\r\nMale,Yes,1,1299,17,Y\r\nMale,No,1,4950,125,Y\r\nMale,No,,3596,100,Y\r\nFemale,No,0,3510,76,N\r\nMale,Yes,1,4887,133,N\r\nMale,Yes,1,2600,115,Y\r\nMale,Yes,0,7660,104,N\r\nMale,Yes,1,5955,315,Y\r\nMale,Yes,0,2600,116,N\r\n,Yes,0,3365,112,N\r\nMale,Yes,,3717,151,N\r\nMale,Yes,1,9560,191,Y\r\nMale,Yes,1,2799,122,Y\r\nMale,Yes,1,4226,110,Y\r\nMale,No,1,1442,35,N\r\nFemale,No,1,3750,120,Y\r\nMale,Yes,,4166,201,N\r\nMale,No,1,3167,74,N\r\nMale,No,1,4692,106,N\r\nMale,Yes,1,3500,114,Y\r\nMale,No,1,12500,320,N\r\nMale,Yes,1,2275,,Y\r\nMale,Yes,0,1828,100,N\r\nFemale,Yes,1,3667,144,Y\r\nMale,No,

In [ ]:
df  = pd.read_csv('01Exercise1.csv')

In [ ]:
df

gender married   ch  income  loanamt status
0      Male      No  1.0    5849      NaN      Y
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[614 rows x 6 columns]

In [ ]:
df.head()

gender married   ch  income  loanamt status
0   Male      No  1.0    5849      NaN      Y
1   Male     Yes  1.0    4583    128.0      N
2   Male     Yes  1.0    3000     66.0      Y
3   Male     Yes  1.0    2583    120.0      Y
4   Male      No  1.0    6000    141.0      Y

In [ ]:
df.tail()

gender married   ch  income  loanamt status
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

In [ ]:
df.shape

(614, 6)

In [ ]:
df.info

<bound method DataFrame.info of      gender married   ch  income  loanamt status
0      Male      No  1.0    5849      NaN      Y
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[614 rows x 6 columns]>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   601 non-null    object 
 1   married  611 non-null    object 
 2   ch       564 non-null    float64
 3   income   614 non-null    int64  
 4   loanamt  592 non-null    float64
 5   status   614 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 28.9+ KB


In [ ]:
df.describe()

ch        income     loanamt
count  564.000000    614.000000  592.000000
mean     0.842199   5403.459283  146.412162
std      0.364878   6109.041673   85.587325
min      0.000000    150.000000    9.000000
25%      1.000000   2877.500000  100.000000
50%      1.000000   3812.500000  128.000000
75%      1.000000   5795.000000  168.000000
max      1.000000  81000.000000  700.000000

In [ ]:
df.isnull().sum(axis = 0)

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df

gender married   ch  income  loanamt status
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
5      Male     Yes  1.0    5417    267.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[529 rows x 6 columns]

In [ ]:
df = df.drop(['gender'],axis = 1)

In [ ]:
df

married   ch  income  loanamt status
1       Yes  1.0    4583    128.0      N
2       Yes  1.0    3000     66.0      Y
3       Yes  1.0    2583    120.0      Y
4        No  1.0    6000    141.0      Y
5       Yes  1.0    5417    267.0      Y
..      ...  ...     ...      ...    ...
609      No  1.0    2900     71.0      Y
610     Yes  1.0    4106     40.0      Y
611     Yes  1.0    8072    253.0      Y
612     Yes  1.0    7583    187.0      Y
613      No  0.0    4583    133.0      N

[529 rows x 5 columns]

In [ ]:
df.dtypes
df = pd.get_dummies(df,drop_first = True)

In [ ]:
df

ch  income  loanamt  married_Yes  status_Y
1    1.0    4583    128.0            1         0
2    1.0    3000     66.0            1         1
3    1.0    2583    120.0            1         1
4    1.0    6000    141.0            0         1
5    1.0    5417    267.0            1         1
..   ...     ...      ...          ...       ...
609  1.0    2900     71.0            0         1
610  1.0    4106     40.0            1         1
611  1.0    8072    253.0            1         1
612  1.0    7583    187.0            1         1
613  0.0    4583    133.0            0         0

[529 rows x 5 columns]

In [ ]:
X = df.iloc[:,0:4].values
Y = df.iloc[:,4:5].values

In [ ]:
X

array([[1.000e+00, 4.583e+03, 1.280e+02, 1.000e+00],
       [1.000e+00, 3.000e+03, 6.600e+01, 1.000e+00],
       [1.000e+00, 2.583e+03, 1.200e+02, 1.000e+00],
       ...,
       [1.000e+00, 8.072e+03, 2.530e+02, 1.000e+00],
       [1.000e+00, 7.583e+03, 1.870e+02, 1.000e+00],
       [0.000e+00, 4.583e+03, 1.330e+02, 0.000e+00]])

In [ ]:
Y

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [ ]:
Y = df[['status_Y']]
X = df.drop(['status_Y'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = \
train_test_split(X, Y, test_size = 0.3, random_state = 1234, stratify=Y)

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [ ]:
Y_predict = svc.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_predict)

In [ ]:
cm

array([[  0,  49],
       [  0, 110]])

In [ ]:
score = svc.score(X_test,Y_test)

In [ ]:
score

0.6918238993710691